#配置从spring cloud config server中获取
#spring:
#  datasource:
#    hikari:
#      connection-test-query: select 1
#      minimum-idle: 1
#      maximum-pool-size: 5
#      auto-commit: false
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ch03
#    username: "postgres"
#    password: "dev"
#    platform: postgres
#    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    database: postgresql
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    ## fix pssql exception
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
