server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # 不使用Eureka服务进行注册
    fetch-registry: false       #不在本地缓存注册信息
    service-url:
      defaultZone: http://localhost:8761
  server:
    wait-time-in-ms-when-sync-empty: 5 #